import logging
import re
import time
from abc import ABC, abstractmethod
from typing import Any

import httpx
from pydantic import BaseModel, Field

from app.core.config import Settings, settings

logger = logging.getLogger(__name__)


class LLMResponse(BaseModel):
    """Normalized response returned from an LLM provider."""

    content: str = Field(..., description="Raw text generated by the model")
    model: str = Field(..., description="Model identifier used for generation")
    provider: str = Field(..., description="Name of the LLM provider")
    usage: dict[str, Any] = Field(
        default_factory=dict, description="Token counts and latency metadata"
    )


class BaseLLMProvider(ABC):
    """Abstract interface for LLM completion providers."""

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        """Generate text completion from prompt."""
        pass


class MockLLMProvider(BaseLLMProvider):
    """Deterministic mock provider for testing and offline execution."""

    def __init__(
        self,
        mock_response: str | None = None,
        model: str = "mock-model",
        provider: str = "mock",
        fail: bool = False,
        failure_message: str = "Mock LLM provider encountered a simulated failure.",
    ) -> None:
        self.mock_response = mock_response
        self.model = model
        self.provider = provider
        self.fail = fail
        self.failure_message = failure_message

    def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        if self.fail:
            raise RuntimeError(self.failure_message)

        if self.mock_response is not None:
            return LLMResponse(
                content=self.mock_response,
                model=self.model,
                provider=self.provider,
                usage={"prompt_tokens": 10, "completion_tokens": 15, "total_tokens": 25},
            )

        # ponytail: deterministic grounding mock extracting cited evidence references from prompt
        evidence_matches = re.findall(r"\[Evidence\s+(\d+)\]", prompt, re.IGNORECASE)
        ev_ref = f"[Evidence {evidence_matches[0]}]" if evidence_matches else "[Evidence 1]"

        # Extract user question excerpt if present
        question_match = re.search(
            r"--- USER QUESTION ---\s*(.*?)\s*--- END USER QUESTION ---",
            prompt,
            re.DOTALL,
        )
        q_text = question_match.group(1).strip() if question_match else "the question"

        content = (
            f"Based on the provided evidence {ev_ref}, DocuLens AI answers '{q_text}' "
            f"directly using grounded document context."
        )

        return LLMResponse(
            content=content,
            model=self.model,
            provider=self.provider,
            usage={"prompt_tokens": 20, "completion_tokens": 20, "total_tokens": 40},
        )


class ProviderError(Exception):
    """Base exception for LLM provider failures."""
    pass


class ProviderTimeoutError(ProviderError):
    """Raised when LLM provider request times out."""
    pass


class ProviderRateLimitError(ProviderError):
    """Raised when LLM provider rate limit is exceeded."""
    pass


class ProviderAuthenticationError(ProviderError):
    """Raised when LLM provider authentication fails."""
    pass


class ProviderUnavailableError(ProviderError):
    """Raised when LLM provider service is unavailable."""
    pass


class OpenAICompatibleProvider(BaseLLMProvider):
    """OpenAI-compatible HTTP provider supporting Google Gemini, OpenAI, Ollama, vLLM, and OpenRouter."""

    def __init__(
        self,
        api_key: str | None = None,
        base_url: str = "https://generativelanguage.googleapis.com/v1beta/openai",
        model: str = "gemini-3.7-flash",
        temperature: float = 0.0,
        max_tokens: int = 1000,
        timeout: float = 30.0,
        max_retries: int = 2,
        provider_name: str = "gemini",
    ) -> None:
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.timeout = timeout
        self.max_retries = max(0, max_retries)
        self.provider_name = provider_name

    def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        messages: list[dict[str, str]] = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        headers: dict[str, str] = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        payload: dict[str, Any] = {
            "model": kwargs.get("model", self.model),
            "messages": messages,
            "temperature": kwargs.get("temperature", self.temperature),
            "max_tokens": kwargs.get("max_tokens", self.max_tokens),
        }

        url = f"{self.base_url}/chat/completions"

        last_exception: Exception | None = None
        for attempt in range(self.max_retries + 1):
            try:
                with httpx.Client(timeout=self.timeout) as client:
                    response = client.post(url, headers=headers, json=payload)
                    response.raise_for_status()
                    try:
                        data = response.json()
                    except Exception as exc:
                        raise ProviderError(
                            f"Malformed response from LLM provider: Invalid JSON: {str(exc)}"
                        ) from exc

                if (
                    not isinstance(data, dict)
                    or "choices" not in data
                    or not isinstance(data["choices"], list)
                    or len(data["choices"]) == 0
                ):
                    raise ProviderError(
                        "Malformed LLM provider response: missing or empty choices."
                    )

                choice = data["choices"][0]
                if not isinstance(choice, dict) or "message" not in choice:
                    raise ProviderError("Malformed LLM provider response: missing message in choice.")

                message_obj = choice.get("message") or {}
                content = message_obj.get("content")
                if content is None:
                    raise ProviderError("Malformed LLM provider response: missing content in message.")

                model_used = data.get("model", self.model)
                usage_raw = data.get("usage") or {}
                usage = {
                    "prompt_tokens": usage_raw.get("prompt_tokens", 0),
                    "completion_tokens": usage_raw.get("completion_tokens", 0),
                    "total_tokens": usage_raw.get("total_tokens", 0),
                }

                return LLMResponse(
                    content=str(content),
                    model=model_used,
                    provider=self.provider_name,
                    usage=usage,
                )
            except httpx.TimeoutException as exc:
                from app.core.metrics import metrics_collector
                metrics_collector.record_provider_timeout()
                last_exception = ProviderTimeoutError(
                    f"LLM provider request timed out after {self.timeout} seconds."
                )
                if attempt < self.max_retries:
                    time.sleep(min(0.5 * (2**attempt), 2.0))
                    continue
                raise last_exception from exc
            except httpx.HTTPStatusError as exc:
                status_code = exc.response.status_code
                if status_code in (429, 500, 502, 503, 504) and attempt < self.max_retries:
                    logger.warning(
                        f"LLM provider returned HTTP {status_code}, retrying attempt {attempt + 1}/{self.max_retries}..."
                    )
                    time.sleep(min(0.5 * (2**attempt), 2.0))
                    continue

                if status_code == 429:
                    from app.core.metrics import metrics_collector
                    metrics_collector.record_provider_rate_limit()
                    raise ProviderRateLimitError(
                        "LLM provider rate limit exceeded. Please retry after waiting."
                    ) from exc
                if status_code in (401, 403):
                    raise ProviderAuthenticationError(
                        "LLM provider authentication failed. Please check your API key."
                    ) from exc
                if status_code >= 500:
                    raise ProviderUnavailableError(
                        f"LLM provider service is temporarily unavailable (HTTP {status_code})."
                    ) from exc
                raise ProviderError(
                    f"LLM provider API request failed with status code {status_code}."
                ) from exc
            except (httpx.ConnectError, httpx.NetworkError) as exc:
                last_exception = ProviderUnavailableError(
                    f"LLM provider connection failed: {type(exc).__name__}: {str(exc)}"
                )
                if attempt < self.max_retries:
                    time.sleep(min(0.5 * (2**attempt), 2.0))
                    continue
                raise last_exception from exc
            except (ProviderError, ProviderTimeoutError, ProviderRateLimitError, ProviderAuthenticationError, ProviderUnavailableError):
                raise
            except Exception as exc:
                raise ProviderError(
                    f"LLM provider request failed: {type(exc).__name__}: {str(exc)}"
                ) from exc

        if last_exception:
            raise last_exception
        raise ProviderError("LLM provider request failed with unknown error.")


# Alias for explicit Google Gemini provider usage
GoogleGeminiProvider = OpenAICompatibleProvider


def get_llm_provider(settings_obj: Settings | None = None) -> BaseLLMProvider:
    """Factory creating configured LLM provider according to application settings."""
    cfg = settings_obj or settings

    if cfg.LLM_PROVIDER == "gemini":
        api_key = (cfg.GEMINI_API_KEY or cfg.LLM_API_KEY).get_secret_value()
        return OpenAICompatibleProvider(
            api_key=api_key,
            base_url=cfg.GEMINI_BASE_URL,
            model=cfg.LLM_MODEL,
            temperature=cfg.LLM_TEMPERATURE,
            max_tokens=cfg.LLM_MAX_TOKENS,
            timeout=cfg.LLM_TIMEOUT,
            max_retries=cfg.LLM_MAX_RETRIES,
            provider_name="gemini",
        )

    if cfg.LLM_PROVIDER == "openai":
        api_key = cfg.LLM_API_KEY.get_secret_value() if cfg.LLM_API_KEY else None
        return OpenAICompatibleProvider(
            api_key=api_key,
            base_url=cfg.LLM_BASE_URL,
            model=cfg.LLM_MODEL,
            temperature=cfg.LLM_TEMPERATURE,
            max_tokens=cfg.LLM_MAX_TOKENS,
            timeout=cfg.LLM_TIMEOUT,
            max_retries=cfg.LLM_MAX_RETRIES,
            provider_name="openai",
        )

    return MockLLMProvider(model=cfg.LLM_MODEL)


llm_provider = get_llm_provider()
