import re
from abc import ABC, abstractmethod
from typing import Any

import httpx
from pydantic import BaseModel, Field

from app.core.config import Settings, settings


class LLMResponse(BaseModel):
    """Normalized response returned from an LLM provider."""

    content: str = Field(..., description="Raw text generated by the model")
    model: str = Field(..., description="Model identifier used for generation")
    provider: str = Field(..., description="Name of the LLM provider")
    usage: dict[str, Any] = Field(
        default_factory=dict, description="Token counts and latency metadata"
    )


class BaseLLMProvider(ABC):
    """Abstract interface for LLM completion providers."""

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        """Generate text completion from prompt."""
        pass


class MockLLMProvider(BaseLLMProvider):
    """Deterministic mock provider for testing and offline execution."""

    def __init__(
        self,
        mock_response: str | None = None,
        model: str = "mock-model",
        provider: str = "mock",
        fail: bool = False,
        failure_message: str = "Mock LLM provider encountered a simulated failure.",
    ) -> None:
        self.mock_response = mock_response
        self.model = model
        self.provider = provider
        self.fail = fail
        self.failure_message = failure_message

    def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        if self.fail:
            raise RuntimeError(self.failure_message)

        if self.mock_response is not None:
            return LLMResponse(
                content=self.mock_response,
                model=self.model,
                provider=self.provider,
                usage={"prompt_tokens": 10, "completion_tokens": 15, "total_tokens": 25},
            )

        # ponytail: deterministic grounding mock extracting cited evidence references from prompt
        evidence_matches = re.findall(r"\[Evidence\s+(\d+)\]", prompt, re.IGNORECASE)
        ev_ref = f"[Evidence {evidence_matches[0]}]" if evidence_matches else "[Evidence 1]"

        # Extract user question excerpt if present
        question_match = re.search(
            r"--- USER QUESTION ---\s*(.*?)\s*--- END USER QUESTION ---",
            prompt,
            re.DOTALL,
        )
        q_text = question_match.group(1).strip() if question_match else "the question"

        content = (
            f"Based on the provided evidence {ev_ref}, DocuLens AI answers '{q_text}' "
            f"directly using grounded document context."
        )

        return LLMResponse(
            content=content,
            model=self.model,
            provider=self.provider,
            usage={"prompt_tokens": 20, "completion_tokens": 20, "total_tokens": 40},
        )


class OpenAICompatibleProvider(BaseLLMProvider):
    """OpenAI-compatible HTTP provider supporting Google Gemini, OpenAI, Ollama, vLLM, and OpenRouter."""

    def __init__(
        self,
        api_key: str | None = None,
        base_url: str = "https://generativelanguage.googleapis.com/v1beta/openai",
        model: str = "gemini-3.7-flash",
        temperature: float = 0.0,
        max_tokens: int = 1000,
        timeout: float = 30.0,
        provider_name: str = "gemini",
    ) -> None:
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.timeout = timeout
        self.provider_name = provider_name

    def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        messages: list[dict[str, str]] = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        headers: dict[str, str] = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        payload: dict[str, Any] = {
            "model": kwargs.get("model", self.model),
            "messages": messages,
            "temperature": kwargs.get("temperature", self.temperature),
            "max_tokens": kwargs.get("max_tokens", self.max_tokens),
        }

        url = f"{self.base_url}/chat/completions"

        try:
            with httpx.Client(timeout=self.timeout) as client:
                response = client.post(url, headers=headers, json=payload)
                response.raise_for_status()
                data = response.json()

            choice = data["choices"][0]
            content = choice["message"]["content"]
            model_used = data.get("model", self.model)
            usage = data.get("usage", {})

            return LLMResponse(
                content=content,
                model=model_used,
                provider=self.provider_name,
                usage=usage,
            )
        except httpx.HTTPStatusError as exc:
            # Safe error message without leaking auth headers or keys
            status_code = exc.response.status_code
            raise RuntimeError(
                f"LLM provider API request failed with status code {status_code}."
            ) from exc
        except Exception as exc:
            raise RuntimeError(
                f"LLM provider request failed: {type(exc).__name__}: {str(exc)}"
            ) from exc


# Alias for explicit Google Gemini provider usage
GoogleGeminiProvider = OpenAICompatibleProvider


def get_llm_provider(settings_obj: Settings | None = None) -> BaseLLMProvider:
    """Factory creating configured LLM provider according to application settings."""
    cfg = settings_obj or settings

    if cfg.LLM_PROVIDER == "gemini":
        api_key = cfg.GEMINI_API_KEY or cfg.LLM_API_KEY
        return OpenAICompatibleProvider(
            api_key=api_key,
            base_url=cfg.GEMINI_BASE_URL,
            model=cfg.LLM_MODEL,
            temperature=cfg.LLM_TEMPERATURE,
            max_tokens=cfg.LLM_MAX_TOKENS,
            provider_name="gemini",
        )

    if cfg.LLM_PROVIDER == "openai":
        return OpenAICompatibleProvider(
            api_key=cfg.LLM_API_KEY,
            base_url=cfg.LLM_BASE_URL,
            model=cfg.LLM_MODEL,
            temperature=cfg.LLM_TEMPERATURE,
            max_tokens=cfg.LLM_MAX_TOKENS,
            provider_name="openai",
        )

    return MockLLMProvider(model=cfg.LLM_MODEL)


llm_provider = get_llm_provider()
